var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/devis/[numero]/duplicate/route.js")
R.c("server/chunks/node_modules_0xt6fmq._.js")
R.c("server/chunks/node_modules_0gnf0qa._.js")
R.c("server/chunks/[root-of-the-server]__0d6.nih._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/node_modules_@clerk_12~4a.6._.js")
R.c("server/chunks/_next-internal_server_app_api_devis_[numero]_duplicate_route_actions_0t.3h5j.js")
R.m(43734)
module.exports=R.m(43734).exports
