var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/devis/[numero]/statut/route.js")
R.c("server/chunks/node_modules_0woue~n._.js")
R.c("server/chunks/node_modules_0gnf0qa._.js")
R.c("server/chunks/[root-of-the-server]__0d6.nih._.js")
R.c("server/chunks/[root-of-the-server]__0_~_1-l._.js")
R.c("server/chunks/node_modules_next_dist_12gp6q5._.js")
R.c("server/chunks/node_modules_@clerk_12~4a.6._.js")
R.c("server/chunks/_next-internal_server_app_api_devis_[numero]_statut_route_actions_0~pvc...js")
R.m(94043)
module.exports=R.m(94043).exports
